// Initial job data
export const initialJobs = [
    {
        id: 1,
        title: "UI UX Designer",
        company: "VR PI Group",
        location: "Hyderabad",
        type: "Remote",
        duration: "Full-Time",
        salary: "₹3-6 Lacs P.A.",
        experience: "0-1",
        postedTime: "5h ago",
        description: "We are looking for a creative UI/UX Designer to design user-friendly web and mobile applications with strong visual and interaction skills.",
        skills: ["User Research", "Wireframing", "Figma", "Prototyping"],
        category: "recommended"
    },
    {
        id: 2,
        title: "Frontend Developer",
        company: "VR PI Group",
        location: "Bangalore",
        type: "Hybrid",
        duration: "Full-Time",
        salary: "₹4-8 Lacs P.A.",
        experience: "1-3",
        postedTime: "2d ago",
        description: "Seeking a skilled Frontend Developer to build responsive and high-performance web applications using modern JavaScript frameworks.",
        skills: ["React.js", "JavaScript", "Tailwind CSS", "REST APIs"],
        category: "recommended"
    },
    {
        id: 3,
        title: "Digital Marketing Executive",
        company: "VR PI Group",
        location: "Mumbai",
        type: "On-site",
        duration: "Full-Time",
        salary: "₹2-5 Lacs P.A.",
        experience: "0-1",
        postedTime: "1d ago",
        description: "Looking for a Digital Marketing Executive to manage SEO, social media campaigns, and paid ads to drive brand growth.",
        skills: ["SEO", "Google Ads", "Social Media Marketing", "Analytics"],
        category: "recommended"
    },
    {
        id: 4,
        title: "Frontend Developer",
        company: "VR PI Group",
        location: "Bangalore",
        type: "On-site",
        duration: "Full-Time",
        salary: "₹5-8 Lacs P.A.",
        experience: "2-5",
        postedTime: "3h ago",
        description: "Looking for experienced React developer with modern frontend skills.",
        skills: ["React", "TypeScript", "Tailwind CSS"],
        category: "recommended"
    },
    {
        id: 5,
        title: "Product Designer",
        company: "VR PI Group",
        location: "Mumbai",
        type: "Hybrid",
        duration: "Full-Time",
        salary: "₹6-10 Lacs P.A.",
        experience: "3-5",
        postedTime: "2h ago",
        description: "Create beautiful user experiences for our digital products.",
        skills: ["Product Design", "User Research", "Prototyping"],
        category: "recommended"
    },
    {
        id: 6,
        title: "Backend Developer",
        company: "VR PI Group",
        location: "Delhi",
        type: "Remote",
        duration: "Full-Time",
        salary: "₹7-12 Lacs P.A.",
        experience: "3-5",
        postedTime: "4h ago",
        description: "Build scalable backend systems using Node.js and cloud technologies.",
        skills: ["Node.js", "AWS", "MongoDB"],
        category: "recommended"
    },
    {
        id: 7,
        title: "Mobile Developer",
        company: "VR PI Group",
        location: "Pune",
        type: "On-site",
        duration: "Full-Time",
        salary: "₹5-9 Lacs P.A.",
        experience: "2-5",
        postedTime: "6h ago",
        description: "Develop cross-platform mobile applications using React Native.",
        skills: ["React Native", "iOS", "Android"],
        category: "recommended"
    },
    {
        id: 8,
        title: "DevOps Engineer",
        company: "VR PI Group",
        location: "Chennai",
        type: "Remote",
        duration: "Full-Time",
        salary: "₹8-14 Lacs P.A.",
        experience: "3-5",
        postedTime: "1h ago",
        description: "Manage CI/CD pipelines and cloud infrastructure.",
        skills: ["Docker", "Kubernetes", "Jenkins"],
        category: "recommended"
    },
    {
        id: 9,
        title: "Data Scientist",
        company: "VR PI Group",
        location: "Hyderabad",
        type: "Hybrid",
        duration: "Full-Time",
        salary: "₹10-16 Lacs P.A.",
        experience: "5-8",
        postedTime: "7h ago",
        description: "Apply machine learning to solve business problems.",
        skills: ["Python", "Machine Learning", "TensorFlow"],
        category: "recommended"
    },
    {
        id: 10,
        title: "QA Engineer",
        company: "VR PI Group",
        location: "Bangalore",
        type: "On-site",
        duration: "Full-Time",
        salary: "₹4-7 Lacs P.A.",
        experience: "1-3",
        postedTime: "5h ago",
        description: "Ensure software quality through comprehensive testing strategies.",
        skills: ["Automation Testing", "Selenium", "API Testing"],
        category: "recommended"
    },
    {
        id: 11,
        title: "Full Stack Developer",
        company: "TechNova Solutions",
        location: "Bangalore",
        type: "Remote",
        duration: "Full-Time",
        salary: "₹6-11 Lacs P.A.",
        experience: "2-5",
        postedTime: "5h ago",
        description: "Work on cutting-edge web applications using modern stack.",
        skills: ["React", "Node.js", "PostgreSQL"],
        category: "latest"
    },
    {
        id: 12,
        title: "UI UX Designer",
        company: "DesignHub India",
        location: "Hyderabad",
        type: "Remote",
        duration: "Full-Time",
        salary: "₹3-6 Lacs P.A.",
        experience: "0-1",
        postedTime: "5h ago",
        description: "When fringilla nisl rutrum magna et risus dui nullafring nisl rutrum magna et risus dui nulla.",
        skills: ["user interface designing", "UI/UX Designing", "Figma"],
        category: "latest"
    },
    {
        id: 13,
        title: "Content Writer",
        company: "ContentCraft Studios",
        location: "Mumbai",
        type: "Hybrid",
        duration: "Full-Time",
        salary: "₹3-5 Lacs P.A.",
        experience: "0-1",
        postedTime: "4h ago",
        description: "Create engaging content for digital platforms.",
        skills: ["Content Writing", "SEO", "Copywriting"],
        category: "latest"
    },
    {
        id: 14,
        title: "Digital Marketing Manager",
        company: "GrowthMax Digital",
        location: "Delhi",
        type: "On-site",
        duration: "Full-Time",
        salary: "₹5-9 Lacs P.A.",
        experience: "3-5",
        postedTime: "6h ago",
        description: "Lead digital marketing campaigns and strategy.",
        skills: ["Digital Marketing", "Google Ads", "Analytics"],
        category: "latest"
    },
    {
        id: 15,
        title: "Business Analyst",
        company: "DataEdge Consulting",
        location: "Pune",
        type: "Hybrid",
        duration: "Full-Time",
        salary: "₹6-10 Lacs P.A.",
        experience: "2-5",
        postedTime: "3h ago",
        description: "Analyze business requirements and propose solutions.",
        skills: ["Business Analysis", "SQL", "Excel"],
        category: "latest"
    },
    {
        id: 16,
        title: "Project Manager",
        company: "Infinite IT Services",
        location: "Bangalore",
        type: "On-site",
        duration: "Full-Time",
        salary: "₹10-18 Lacs P.A.",
        experience: "5-8",
        postedTime: "2h ago",
        description: "Manage complex software development projects.",
        skills: ["Project Management", "Agile", "Scrum"],
        category: "latest"
    },
    {
        id: 17,
        title: "Graphic Designer",
        company: "CreativeMinds Agency",
        location: "Mumbai",
        type: "Remote",
        duration: "Full-Time",
        salary: "₹4-7 Lacs P.A.",
        experience: "1-3",
        postedTime: "5h ago",
        description: "Design visual content for brands and campaigns.",
        skills: ["Adobe Creative Suite", "Branding", "Illustration"],
        category: "latest"
    },
    {
        id: 18,
        title: "Sales Executive",
        company: "SalesForce India",
        location: "Delhi",
        type: "On-site",
        duration: "Full-Time",
        salary: "₹3-6 Lacs P.A.",
        experience: "0-1",
        postedTime: "7h ago",
        description: "Drive sales growth and customer acquisition.",
        skills: ["Sales", "Communication", "CRM"],
        category: "latest"
    },
    {
        id: 19,
        title: "HR Manager",
        company: "PeopleFirst HR Solutions",
        location: "Hyderabad",
        type: "Hybrid",
        duration: "Full-Time",
        salary: "₹5-9 Lacs P.A.",
        experience: "3-5",
        postedTime: "4h ago",
        description: "Lead HR operations and talent management.",
        skills: ["HR Management", "Recruitment", "Employee Relations"],
        category: "latest"
    },
    {
        id: 20,
        title: "Financial Analyst",
        company: "FinanceGuru Corp",
        location: "Mumbai",
        type: "On-site",
        duration: "Full-Time",
        salary: "₹6-11 Lacs P.A.",
        experience: "2-5",
        postedTime: "6h ago",
        description: "Analyze financial data and provide insights.",
        skills: ["Financial Analysis", "Excel", "Modeling"],
        category: "latest"
    },
    {
        id: 21,
        title: "Product Manager",
        company: "ProductVision Labs",
        location: "Bangalore",
        type: "Remote",
        duration: "Full-Time",
        salary: "₹12-20 Lacs P.A.",
        experience: "5-8",
        postedTime: "3h ago",
        description: "Define product strategy and roadmap.",
        skills: ["Product Management", "Strategy", "Analytics"],
        category: "latest"
    },
    {
        id: 22,
        title: "Customer Success Manager",
        company: "ClientFirst Technologies",
        location: "Pune",
        type: "Hybrid",
        duration: "Full-Time",
        salary: "₹5-8 Lacs P.A.",
        experience: "2-5",
        postedTime: "5h ago",
        description: "Ensure customer satisfaction and retention.",
        skills: ["Customer Success", "Communication", "Problem Solving"],
        category: "latest"
    },
    {
        id: 23,
        title: "Security Engineer",
        company: "CyberGuard Systems",
        location: "Delhi",
        type: "Remote",
        duration: "Full-Time",
        salary: "₹8-15 Lacs P.A.",
        experience: "3-5",
        postedTime: "2h ago",
        description: "Protect systems from security threats.",
        skills: ["Cybersecurity", "Penetration Testing", "Security Audits"],
        category: "latest"
    },
    {
        id: 24,
        title: "Video Editor",
        company: "MediaWorks Studio",
        location: "Mumbai",
        type: "On-site",
        duration: "Full-Time",
        salary: "₹4-6 Lacs P.A.",
        experience: "1-3",
        postedTime: "6h ago",
        description: "Edit and produce video content.",
        skills: ["Video Editing", "Premiere Pro", "After Effects"],
        category: "latest"
    },
    {
        id: 25,
        title: "System Administrator",
        company: "ITOps Solutions",
        location: "Chennai",
        type: "On-site",
        duration: "Full-Time",
        salary: "₹4-7 Lacs P.A.",
        experience: "1-3",
        postedTime: "7h ago",
        description: "Maintain and manage IT infrastructure.",
        skills: ["System Administration", "Linux", "Networking"],
        category: "latest"
    },
    {
        id: 26,
        title: "UX Researcher",
        company: "UserFirst Research",
        location: "Bangalore",
        type: "Hybrid",
        duration: "Full-Time",
        salary: "₹6-10 Lacs P.A.",
        experience: "2-5",
        postedTime: "4h ago",
        description: "Conduct user research and usability studies.",
        skills: ["User Research", "Usability Testing", "Data Analysis"],
        category: "latest"
    },
    {
        id: 27,
        title: "Blockchain Developer",
        company: "ChainTech Innovations",
        location: "Remote",
        type: "Remote",
        duration: "Full-Time",
        salary: "₹10-18 Lacs P.A.",
        experience: "3-5",
        postedTime: "5h ago",
        description: "Develop blockchain-based applications.",
        skills: ["Blockchain", "Solidity", "Smart Contracts"],
        category: "latest"
    },
    {
        id: 28,
        title: "Technical Writer",
        company: "DocuTech Solutions",
        location: "Hyderabad",
        type: "Remote",
        duration: "Full-Time",
        salary: "₹4-7 Lacs P.A.",
        experience: "1-3",
        postedTime: "3h ago",
        description: "Create technical documentation and guides.",
        skills: ["Technical Writing", "Documentation", "Communication"],
        category: "latest"
    },
    {
        id: 29,
        title: "SEO Specialist",
        company: "RankBoost Digital",
        location: "Delhi",
        type: "Hybrid",
        duration: "Full-Time",
        salary: "₹3-6 Lacs P.A.",
        experience: "1-3",
        postedTime: "6h ago",
        description: "Optimize websites for search engines.",
        skills: ["SEO", "Google Analytics", "Content Strategy"],
        category: "latest"
    },
    {
        id: 30,
        title: "Cloud Architect",
        company: "CloudScale Technologies",
        location: "Bangalore",
        type: "Remote",
        duration: "Full-Time",
        salary: "₹15-25 Lacs P.A.",
        experience: "5-8",
        postedTime: "2h ago",
        description: "Design and implement cloud infrastructure solutions.",
        skills: ["Cloud Architecture", "AWS", "Azure"],
        category: "latest"
    }
];